=pod

=head1 NAME

Graphics::Toolkit::Color::Manual::Cookbook - examples that fix practical issues

=head1 SYNOPSIS

=head1 RECIPES

=head2 How to convert color values?

=head2 How to translate a CSS color name into values?

=head2 How to get a split complementary palette?

=head2 How to get a monochrome palette?


=head1 AUTHOR

Herbert Breunung, <lichtkind@cpan.org>

=head1 COPYRIGHT

Copyright 2026 Herbert Breunung.

=head1 LICENSE

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut
