=pod

=head1 NAME

Graphics::Toolkit::Color::Manual::Cookbook - examples that fix real issues

=head1 SYNOPSIS

=head1 INTRODUCTION


=head1 AUTHOR

Herbert Breunung, <lichtkind@cpan.org>

=head1 COPYRIGHT

Copyright 2026 Herbert Breunung.

=head1 LICENSE

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut
