
=pod

=head1 NAME

Graphics::Toolkit::Color::Manual::Plugin - how to extend GTC

=head1 SYNOPSIS

This L<manual|Graphics::Toolkit::Color::Manual> page explains the two
mechanisms by which the user might extend GTC functionality.


There are mainly two fronts on which GTC is easy to extend without a 
pull request: 

=over 4

=item *

1. creating a new color space

=item *

1. creating a new color naming scheme

=back

=head1 COLOR SPACE

=head1 COLOR SCHEME


=head1 AUTHOR

Herbert Breunung, <lichtkind@cpan.org>

=head1 COPYRIGHT

Copyright 2026 Herbert Breunung.

=head1 LICENSE

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

=cut


